theme: jekyll-theme-minimal
title: "Panza: A personal email assistant, trained and running on a single consumer GPU."
description: "Panza provides the tools to finetune an LLM on your past emails to imitate your style and content."
