theme: jekyll-theme-minimal
title: "Panza: A personal assistant, with Zero attitude."
description: "Panza provides the tools to finetune an LLM on your past emails to imitate your style and content."
